-- +goose up

CREATE TABLE POSTS (
    ID UUID PRIMARY KEY,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    USER_ID UUID NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE,
    FEED_ID UUID NOT NULL REFERENCES FEEDS(ID) ON DELETE CASCADE,
    TITLE TEXT NOT NULL,
    URL TEXT NOT NULL,
    UNIQUE (USER_ID, FEED_ID, URL)
);

-- +goose down
DROP TABLE POSTS;